import './globals.css'
import { Providers } from '@/redux/provider'
import Header from '@/components/Header/Header.component'
import HeaderLink from '@/components/HeaderLink/HeaderLink.component';
import HomeIcon from '@mui/icons-material/Home';


import { ExploreSharp, Margin } from "@mui/icons-material";
// import Link from "next/link";
import { GroupSharp } from "@mui/icons-material";
import { OndemandVideoSharp } from "@mui/icons-material";
import { BusinessCenterSharp } from "@mui/icons-material";
import AccountCircleSharpIcon from "@mui/icons-material/AccountCircleSharp";
import { getTokenFromLocal } from '@/ClientHelper/authHelper';
import StorefrontIcon from '@mui/icons-material/Storefront';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body >
      <Providers>
        <Header />
        {children}

        <div className="flex lg:hidden bg-slate-900 w-full justify-between  h-[10vh]  items-center fixed bottom-0 ">
          <HeaderLink Icon={HomeIcon}  text="Home" link="/home" />
          <HeaderLink Icon={ExploreSharp} text="Explore" link="/explore"/>
          <HeaderLink Icon={OndemandVideoSharp} text="Learning" link="/learning"/>
          <HeaderLink Icon={StorefrontIcon} text="Shop" link="/shop"/>
          <HeaderLink Icon={AccountCircleSharpIcon} link="/profile" text="Profile"   />
        </div>
      </Providers>
      
      
      
     
      
      </body>
    </html>
  )
}
